// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsBackButton = lv_imgbtn_create(ui_SettingsScreen);
    lv_imgbtn_set_src(ui_SettingsBackButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_786474294, NULL);
    lv_obj_set_height(ui_SettingsBackButton, 64);
    lv_obj_set_width(ui_SettingsBackButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SettingsBackButton, -333);
    lv_obj_set_y(ui_SettingsBackButton, -182);
    lv_obj_set_align(ui_SettingsBackButton, LV_ALIGN_CENTER);

    ui_WiFiSettingsButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_WiFiSettingsButton, 347);
    lv_obj_set_height(ui_WiFiSettingsButton, 85);
    lv_obj_set_x(ui_WiFiSettingsButton, 10);
    lv_obj_set_y(ui_WiFiSettingsButton, -113);
    lv_obj_set_align(ui_WiFiSettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSettingsButtonLabel = lv_label_create(ui_WiFiSettingsButton);
    lv_obj_set_width(ui_WifiSettingsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSettingsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSettingsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiSettingsButtonLabel, "WiFi");
    lv_obj_set_style_text_font(ui_WifiSettingsButtonLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsBackButton, ui_event_SettingsBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiSettingsButton, ui_event_WiFiSettingsButton, LV_EVENT_ALL, NULL);
    uic_SettingsScreen = ui_SettingsScreen;
    uic_SettingsBackButton = ui_SettingsBackButton;
    uic_WiFiSettingsButton = ui_WiFiSettingsButton;
    uic_WifiSettingsButtonLabel = ui_WifiSettingsButtonLabel;

}
