// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoistureLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MoistureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoistureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoistureLabel, -99);
    lv_obj_set_y(ui_MoistureLabel, -15);
    lv_obj_set_align(ui_MoistureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoistureLabel, "Moisture:");
    lv_obj_set_style_text_color(ui_MoistureLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoistureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MoistureLabel, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_MoistureLabel = ui_MoistureLabel;

}
