// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TimeScreen_screen_init(void)
{
    ui_TimeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TimeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiScreenBackButton2 = lv_imgbtn_create(ui_TimeScreen);
    lv_imgbtn_set_src(ui_WifiScreenBackButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_786474294, NULL);
    lv_imgbtn_set_src(ui_WifiScreenBackButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_786474294, NULL);
    lv_obj_set_height(ui_WifiScreenBackButton2, 64);
    lv_obj_set_width(ui_WifiScreenBackButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_WifiScreenBackButton2, -352);
    lv_obj_set_y(ui_WifiScreenBackButton2, -191);
    lv_obj_set_align(ui_WifiScreenBackButton2, LV_ALIGN_CENTER);

    ui_TimeLabel = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 1);
    lv_obj_set_y(ui_TimeLabel, -57);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncTimeButton = lv_btn_create(ui_TimeScreen);
    lv_obj_set_width(ui_SyncTimeButton, 332);
    lv_obj_set_height(ui_SyncTimeButton, 64);
    lv_obj_set_x(ui_SyncTimeButton, 6);
    lv_obj_set_y(ui_SyncTimeButton, 68);
    lv_obj_set_align(ui_SyncTimeButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SyncTimeButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_SyncTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SyncTimeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SyncTimeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SyncTimeButton, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SyncTimeButtonLabel = lv_label_create(ui_SyncTimeButton);
    lv_obj_set_width(ui_SyncTimeButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SyncTimeButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SyncTimeButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SyncTimeButtonLabel, "Sync Time");
    lv_obj_set_style_text_font(ui_SyncTimeButtonLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectToWifiSync = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_ConnectToWifiSync, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectToWifiSync, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectToWifiSync, 239);
    lv_obj_set_y(ui_ConnectToWifiSync, 20);
    lv_obj_set_align(ui_ConnectToWifiSync, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ConnectToWifiSync, "Connect to wifi to Sync");
    lv_obj_set_style_text_color(ui_ConnectToWifiSync, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectToWifiSync, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WifiScreenBackButton2, ui_event_WifiScreenBackButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SyncTimeButton, ui_event_SyncTimeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeScreen, ui_event_TimeScreen, LV_EVENT_ALL, NULL);
    uic_TimeScreen = ui_TimeScreen;
    uic_WifiScreenBackButton = ui_WifiScreenBackButton2;
    uic_TimeLabel = ui_TimeLabel;
    uic_SyncTimeButtonLabel = ui_SyncTimeButtonLabel;
    uic_ConnectToWifiSync = ui_ConnectToWifiSync;

}
