// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TimeScreen_screen_init(void)
{
    ui_TimeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TimeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeScreen, lv_color_hex(0x818181), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_TimeScreen, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_WifiScreenBackButton2 = lv_imgbtn_create(ui_TimeScreen);
    lv_imgbtn_set_src(ui_WifiScreenBackButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_786474294, NULL);
    lv_imgbtn_set_src(ui_WifiScreenBackButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_786474294, NULL);
    lv_obj_set_height(ui_WifiScreenBackButton2, 64);
    lv_obj_set_width(ui_WifiScreenBackButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_WifiScreenBackButton2, -352);
    lv_obj_set_y(ui_WifiScreenBackButton2, -191);
    lv_obj_set_align(ui_WifiScreenBackButton2, LV_ALIGN_CENTER);

    ui_TimeLabel = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 12);
    lv_obj_set_y(ui_TimeLabel, -188);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncTimeButton = lv_btn_create(ui_TimeScreen);
    lv_obj_set_width(ui_SyncTimeButton, 231);
    lv_obj_set_height(ui_SyncTimeButton, 64);
    lv_obj_set_x(ui_SyncTimeButton, 263);
    lv_obj_set_y(ui_SyncTimeButton, -88);
    lv_obj_set_align(ui_SyncTimeButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SyncTimeButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_SyncTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SyncTimeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SyncTimeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SyncTimeButton, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SyncTimeButtonLabel = lv_label_create(ui_SyncTimeButton);
    lv_obj_set_width(ui_SyncTimeButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SyncTimeButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SyncTimeButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SyncTimeButtonLabel, "Sync Time");
    lv_obj_set_style_text_font(ui_SyncTimeButtonLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectToWifiSync = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_ConnectToWifiSync, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectToWifiSync, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectToWifiSync, 549);
    lv_obj_set_y(ui_ConnectToWifiSync, -137);
    lv_obj_set_align(ui_ConnectToWifiSync, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ConnectToWifiSync, "Connect to wifi to Sync");
    lv_obj_set_style_text_color(ui_ConnectToWifiSync, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectToWifiSync, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NightTimeSwitch = lv_switch_create(ui_TimeScreen);
    lv_obj_set_width(ui_NightTimeSwitch, 105);
    lv_obj_set_height(ui_NightTimeSwitch, 48);
    lv_obj_set_x(ui_NightTimeSwitch, -308);
    lv_obj_set_y(ui_NightTimeSwitch, -79);
    lv_obj_set_align(ui_NightTimeSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_NightTimeSwitch, lv_color_hex(0xA2A2A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NightTimeSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label10 = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 40);
    lv_obj_set_y(ui_Label10, -118);
    lv_obj_set_align(ui_Label10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label10, "Turn off screen at night");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xE3E3E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NightStartTimeLabel = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_NightStartTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NightStartTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NightStartTimeLabel, -318);
    lv_obj_set_y(ui_NightStartTimeLabel, -29);
    lv_obj_set_align(ui_NightStartTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NightStartTimeLabel, "Turn off at:");
    lv_obj_set_style_text_color(ui_NightStartTimeLabel, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NightStartTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NightEndTimeLabel = lv_label_create(ui_TimeScreen);
    lv_obj_set_width(ui_NightEndTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NightEndTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NightEndTimeLabel, -155);
    lv_obj_set_y(ui_NightEndTimeLabel, -28);
    lv_obj_set_align(ui_NightEndTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NightEndTimeLabel, "Turn on at:");
    lv_obj_set_style_text_color(ui_NightEndTimeLabel, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NightEndTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NightStartTime = lv_textarea_create(ui_TimeScreen);
    lv_obj_set_width(ui_NightStartTime, 115);
    lv_obj_set_height(ui_NightStartTime, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_NightStartTime, -304);
    lv_obj_set_y(ui_NightStartTime, 13);
    lv_obj_set_align(ui_NightStartTime, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_NightStartTime, NULL);
    else lv_textarea_set_accepted_chars(ui_NightStartTime, "0123456789");
    lv_textarea_set_placeholder_text(ui_NightStartTime, "00");
    lv_textarea_set_one_line(ui_NightStartTime, true);
    lv_obj_add_state(ui_NightStartTime, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_align(ui_NightStartTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NightStartTime, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NightStartTime, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_NightStartTime, 255, LV_PART_MAIN | LV_STATE_DISABLED);



    ui_NightEndTime = lv_textarea_create(ui_TimeScreen);
    lv_obj_set_width(ui_NightEndTime, 115);
    lv_obj_set_height(ui_NightEndTime, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_NightEndTime, -141);
    lv_obj_set_y(ui_NightEndTime, 13);
    lv_obj_set_align(ui_NightEndTime, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_NightEndTime, NULL);
    else lv_textarea_set_accepted_chars(ui_NightEndTime, "0123456789");
    lv_textarea_set_placeholder_text(ui_NightEndTime, "00");
    lv_textarea_set_one_line(ui_NightEndTime, true);
    lv_obj_add_state(ui_NightEndTime, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_align(ui_NightEndTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NightEndTime, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NightEndTime, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_NightEndTime, 255, LV_PART_MAIN | LV_STATE_DISABLED);



    ui_TimeScreenKeyboard = lv_keyboard_create(ui_TimeScreen);
    lv_keyboard_set_mode(ui_TimeScreenKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_TimeScreenKeyboard, 800);
    lv_obj_set_height(ui_TimeScreenKeyboard, 194);
    lv_obj_set_x(ui_TimeScreenKeyboard, 0);
    lv_obj_set_y(ui_TimeScreenKeyboard, 145);
    lv_obj_set_align(ui_TimeScreenKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeScreenKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_TimeScreenKeyboard, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeScreenKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TimeScreenKeyboard, lv_color_hex(0xCACACA), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeScreenKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeScreenKeyboard, &lv_font_montserrat_32, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WifiScreenBackButton2, ui_event_WifiScreenBackButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SyncTimeButton, ui_event_SyncTimeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NightTimeSwitch, ui_event_NightTimeSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NightStartTime, ui_event_NightStartTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NightEndTime, ui_event_NightEndTime, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_TimeScreenKeyboard, ui_NightEndTime);
    lv_obj_add_event_cb(ui_TimeScreen, ui_event_TimeScreen, LV_EVENT_ALL, NULL);
    uic_TimeScreen = ui_TimeScreen;
    uic_WifiScreenBackButton = ui_WifiScreenBackButton2;
    uic_TimeLabel = ui_TimeLabel;
    uic_SyncTimeButtonLabel = ui_SyncTimeButtonLabel;
    uic_ConnectToWifiSync = ui_ConnectToWifiSync;
    uic_NightTimeSwitch = ui_NightTimeSwitch;
    uic_NightStartTimeLabel = ui_NightStartTimeLabel;
    uic_NightEndTimeLabel = ui_NightEndTimeLabel;
    uic_NightStartTime = ui_NightStartTime;
    uic_NightEndTime = ui_NightEndTime;
    uic_TimeScreenKeyboard = ui_TimeScreenKeyboard;

}
