// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SetInactivityTimer(lv_event_t * e);
void getWifiStatus(lv_event_t * e);
void readMoisture(lv_event_t * e);
void resetSettings(lv_event_t * e);
void scanWifiNetworks(lv_event_t * e);
void connectToWifi(lv_event_t * e);
void onTimeScreenLoaded(lv_event_t * e);
void syncTime(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
